spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/./data/project
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true  # 추가
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: ALWAYS
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2